# Generated by Django 3.0.6 on 2020-05-25 00:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eskayoriadescrumy', '0002_auto_20200524_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrumyhistory',
            name='goal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rname', to='eskayoriadescrumy.ScrumyGoals'),
        ),
    ]
