# Generated by Django 3.0.6 on 2020-06-06 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eskayoriadescrumy', '0005_auto_20200527_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrumygoals',
            name='goal_name',
            field=models.CharField(max_length=50),
        ),
    ]
