# Generated by Django 3.0.6 on 2020-06-10 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('websocket', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatmessage',
            old_name='messsage',
            new_name='message',
        ),
    ]
