# Generated by Django 3.0.6 on 2020-05-27 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eskayoriadescrumy', '0003_auto_20200525_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrumyhistory',
            name='goal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='eskayoriadescrumy.ScrumyGoals'),
        ),
    ]
