# Generated by Django 3.0.6 on 2020-05-27 12:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eskayoriadescrumy', '0004_auto_20200527_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrumygoals',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rname', to=settings.AUTH_USER_MODEL),
        ),
    ]
